# Detection
- Constructing Visual pun detection dataset, by separating the text and image, image as input , text as label,dataset size is 3400
    - sources: visual pun, visual idiom, emojis, which are recognisable by odinary people
    - no matter from which source, the visual pun should be able to recognised by at least one person (let's say from 30 candidates)
    - In default case , each image should provide enough cue about the type of information expected, telling whether the image is related to a word? phrase? idiom? proverb? slang? celebrity? movie? famous character?
- Testing all the mainstream MLLM's detection abilities (include 4 close-sourced and 4 open-sourced MLLMs)
    - one image can have several similar meaning but different wording interprations, like "blow your mind" and " mind blown" These should be considered the same,
    - the MLLM should first generally describe the picture, Then, should try to come up with the answer. (An ablation study can be conducted to prove the necessity of the decription part)
    - compare the LLMs performance on different type of images sets, and rank the performance
- Why ensembling is the way to go?
    - count the total number of at least one LLM is right
    - 每个参加评测大模型做一个6边形的图，直接评价各模型在各方面的能力,可以识别的形式可以分为：
        - Memoji
        - Minimalist
        - Emoji Combination
        - Visual Pun (should use a pun picture,<b>each word should have a direct cue in the picture</b>) and Metaphorical (more abstractive, without direct use of the word,but the <b> number of this kind is a problem</b>.the difference with visual pun is need to understand an act in an abstracive artistic image )
        - Descriptive illustration( in this case the Model should be able to 
        - Non realistic(encompasses abstract, expressionistic, stylized, cubism and other approaches)
     - 背景知识可以分为(用折现图）：
       - literature( Idiom,proverb,phrase or word)
       - POP culture( Movie,TV series,cartoon,Anime,Game,APP,songs, real image based)
       - fiction (fictional images)
       - real person(real images based)
    - count each 2 LLMs complementary ratio(number of set difference/number of recognised samples)
- <b>Special cases that need to notices:</b>
    - count the total number of unique right, and each LLM's percentage (or number) of unique right
    - number of all right images,
    - number of all wrong images(if label is somewhat wrong,fix it! ),can show some typical cases, that easy for human to recognise but almost impossible for LLMs
- <b> Further Analysis</b>
   - Find the samples that all the LLMs can't recognise, then make another group of humans look through these images, get their recognition rate
   - analyze what special character does these unrecognizable by LLMs images have, try to summarize their common qualities
   - <b>If </b> the unrecognizable by LLM pattern is obserable, In the next work we can come up with a dataset that easy for human's but challenging for LLMs.  <b> It'll be a really great breakthrough!</b> . Of course, this can only be build on the assumption that the challenging pattern is obserable and can be summarized.
- DATA TABLE
    - <b>Image</b>:name of the image file in the folder, eg: 0001.jpg
    - <b>Question</b>: the question attached on the image, guess idiom or guess a phrase or other, there might be more then 10 questions
    - <b>Knowledge type</b>: is it a movie?word?story? or a person?
    - <b>Expression Style</b>: Minimalist? Nonrealisim? Emoji Combination? Memoji?Visual Pun?Illustration?
    - <b>Label</b>:the standard label, more like anchor to the image, eg: alice(alice in the wonderland)
    - <b>Description</b>:explain why the label is right for the image , which elments in the image make it what it is, if it's and idiom or metaphor, further explain the it. eg. if the image is "cry wolf" then should explain it means false alarm 
    - <b>Culture</b>:except from the English(UK,USA,Canada...) ,it can be Latine, Greek,Norse,Slavic,Arabic,Japanese,Chinese,Indian, Even more rare sourced cultures like native american, Hawaiian,Inuit
    - <b>LLMs</b>:during the experiment ,let's first collect the response of each tested LLM as one column, currently, we want to test <b> GPT,Gemini, Claude, Grok,GLM and LLama</b>
    - <b>Num of recognition</b>: range from 0 to 5, 0 means non of 5 LLMs recognised the image , 5 means all five recognised

      

<b>Exploring Distraction in LLMs Through Image Recognition</b>
- If we select a set of images that a language model (LLM) correctly identifies when analyzed individually, and then feed these same images into the model simultaneously, the original correct classifications often turn incorrect. This phenomenon could provide a way to quantify and study the model's susceptibility to distraction or its ability to manage attention.
- A key variable to investigate is the number of images. At what point does this phenomenon begin to appear? Is there a maximum number of images beyond which the accuracy stabilizes, regardless of how many additional images are introduced?
- Another important factor is whether the order of the images in the prompt impacts the results. For example, does the first image receive more attention or priority compared to subsequent ones?
- To gain further insight, we could compare different LLMs. For fairness, the comparison should only involve images that each model has correctly identified when evaluated individually.
- Additionally, it would be interesting to explore an alternative approach: instead of feeding the images separately in a single prompt, what if the images are merged into a single composite image? Would this reduce distraction and improve recognition accuracy, or would it exacerbate the problem?

This approach offers a compelling framework to study the distraction factor in LLMs. While this idea serves as a starting point, a deeper and more sophisticated investigation could form the basis of a detailed research paper.

In [84]:
import base64

def image_to_base64(image_path):
    try:
        with open(image_path, "rb") as image_file:
            # Read the image binary data
            binary_data = image_file.read()
            # Encode binary data to base64
            base64_data = base64.b64encode(binary_data)
            # Convert bytes to string
            base64_string = base64_data.decode('utf-8')
            # Create the complete base64 URL
            base64_url = f"data:image/{image_path.split('.')[-1]};base64,{base64_string}"
            return base64_url
    except Exception as e:
        return f"Error: {str(e)}"

In [88]:
from openai import OpenAI
import httpx

client = OpenAI(
    base_url="https://api.xty.app/v1", 
    api_key=key,
    http_client=httpx.Client(
        base_url="https://api.xty.app/v1",
        follow_redirects=True,
    ),
)
image_path = "3429.jpg" 
completion = client.chat.completions.create(
  model="claude-3-5-sonnet-20241022",
  messages=[
      {
        "role": "user",
        "content": [
          {
            "type": "text",
            "text": "Who is this?"
          },
          {
            "type": "image_url",
            "image_url": {"url":image_to_base64(image_path)}
          }
        ]
      }
    ]
)

print(completion.choices[0].message.content)

This appears to be Pandora from Greek mythology, depicted in the classic black-figure style of ancient Greek pottery art. According to the myth, she was given a box (though it was actually a jar or "pithos" in the original Greek) by the gods, which she opened, releasing all the world's evils. The image shows a female figure in a long flowing dress holding up what appears to be the infamous box, with wispy shapes emerging from it, represented in a traditional Ancient Greek artistic style against an orange background with classical columns.


In [1]:
# Assume openai>=1.0.0
from openai import OpenAI

# Create an OpenAI client with your deepinfra token and endpoint
openai = OpenAI(
    api_key="G0QudzLa9xY2YYUIKqKV6qgbF7HpLyTf",
    base_url="https://api.deepinfra.com/v1/openai",
)

chat_completion = openai.chat.completions.create(
    model="meta-llama/Llama-3.2-90B-Vision-Instruct",
    messages=[{"role": "user", "content": "Hello"}],
)

print(chat_completion.choices[0].message.content)
print(chat_completion.usage.prompt_tokens, chat_completion.usage.completion_tokens)

# Hello! It's nice to meet you. Is there something I can help you with, or would you like to chat?
# 11 25


Hello! It's nice to meet you. Is there something I can help you with or would you like to chat?
11 24


## GPT

## Claude

In [81]:
from openai import OpenAI
import httpx

client = OpenAI(
    base_url="https://api.xty.app/v1", 
    api_key="xxx",
    http_client=httpx.Client(
        base_url="https://api.xty.app/v1",
        follow_redirects=True,
    ),
)

completion = client.chat.completions.create(
  model="gpt-4o",
  messages=[
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "can you describe a given image?"}
  ]
)

print(completion.choices[0].message.content)

I'm unable to view images directly. However, if you describe an image to me, I can help with analysis, provide information, or answer questions about it! Let me know how I can assist you.


In [109]:
import os
import base64
import json
from openai import OpenAI
import requests

def process_images(folder_path):
    client = OpenAI(
    base_url="https://api.xty.app/v1", 
    api_key="xxx",
    http_client=httpx.Client(
        base_url="https://api.xty.app/v1",
        follow_redirects=True,
    ),
    )
    output_file = os.path.join(folder_path, 'infer.json')

    if os.path.exists(output_file):
        with open(output_file, 'r', encoding='utf-8') as f:
            results = json.load(f)
    else:
        results = {}
    
    valid_extensions = ('.jpg', '.jpeg', '.png')
    image_files = [f for f in os.listdir(folder_path) if f.lower().endswith(valid_extensions)]
    
    for img_file in image_files:
        key = os.path.splitext(img_file)[0]
        
        # Skip if already processed
        if key in results:
            print(f"Skipping {img_file} - already processed")
            continue
            
        img_path = os.path.join(folder_path, img_file)
        
        try:
            # Read and encode image with proper data URI format
            with open(img_path, 'rb') as f:
                img_base = base64.b64encode(f.read()).decode('utf-8')
                # Add the appropriate data URI prefix based on file extension
                if img_file.lower().endswith(('.jpg', '.jpeg')):
                    img_base = f"data:image/jpeg;base64,{img_base}"
                elif img_file.lower().endswith('.png'):
                    img_base = f"data:image/png;base64,{img_base}"
                    

            completion = client.chat.completions.create(
              model="gemini-2.0-flash-exp",
              messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content":[{"type": "image_url", "image_url": {"url": img_base}},
                                            {"type": "text", "text": "Concisely answer the question on the image!"}]}
              ]
            )
            value = completion.choices[0].message.content
            results[key] = value
            print(key,'|',value)

            with open(output_file, 'w', encoding='utf-8') as f:
                json.dump(results, f, ensure_ascii=False, indent=2)
            
        except Exception as e:
            print(f"Error processing {img_file}: {str(e)}")
            results[key] = "Error: " + str(e)
            # Save results even if there's an error
            with open(output_file, 'w', encoding='utf-8') as f:
                json.dump(results, f, ensure_ascii=False, indent=2)
    
    return output_file

# Usage
folder_path = "a"
output_file = process_images(folder_path)
print(f"Results saved to: {output_file}")

0650 | Tom Hanks
Results saved to: a\infer.json


## Gemini

In [33]:
import os
import base64
import json
from openai import OpenAI
import requests

def process_images(folder_path):
    url = "https://api.ainewserver.com/v1/chat/completions"
    headers = {
        "Authorization": "xxx",
        "content-type": "application/json"
    }
    output_file = os.path.join(folder_path, 'test.json')
    
    # Load existing results if file exists
    if os.path.exists(output_file):
        with open(output_file, 'r', encoding='utf-8') as f:
            results = json.load(f)
    else:
        results = {}
    
    valid_extensions = ('.jpg', '.jpeg', '.png')
    image_files = [f for f in os.listdir(folder_path) if f.lower().endswith(valid_extensions)]
    
    for img_file in image_files:
        key = os.path.splitext(img_file)[0]
        
        # Skip if already processed
        if key in results:
            print(f"Skipping {img_file} - already processed")
            continue
            
        img_path = os.path.join(folder_path, img_file)
        
        try:
            # Read and encode image with proper data URI format
            with open(img_path, 'rb') as f:
                img_base = base64.b64encode(f.read()).decode('utf-8')
                # Add the appropriate data URI prefix based on file extension
                if img_file.lower().endswith(('.jpg', '.jpeg')):
                    img_base = f"data:image/jpeg;base64,{img_base}"
                elif img_file.lower().endswith('.png'):
                    img_base = f"data:image/png;base64,{img_base}"
                    
            data = {
                "messages":[
                    {
                        "role": "user",
                        "content":[{"type": "image_url", "image_url": {"url": img_base}},
                                   {"type": "text", "text": "concisely answer the question on the image"}]
                    }],
                "model": "claude-3-5-sonnet-20241022"
            }
         
            response = requests.post(url, headers=headers, json=data)
            data = json.loads(response.text)
            value = data['choices'][0]['message']['content']   
            results[key] = value
            print(key,'|',value)
            
            # Save results after each successful processing
            with open(output_file, 'w', encoding='utf-8') as f:
                json.dump(results, f, ensure_ascii=False, indent=2)
            
        except Exception as e:
            print(f"Error processing {img_file}: {str(e)}")
            results[key] = "Error: " + str(e)
            # Save results even if there's an error
            with open(output_file, 'w', encoding='utf-8') as f:
                json.dump(results, f, ensure_ascii=False, indent=2)
    
    return output_file

# Usage
folder_path = "test"
output_file = process_images(folder_path)
print(f"Results saved to: {output_file}")

0001 | I don't see a question in the image - it appears to be a large grid of cells or boxes. Could you please let me know what specific question you'd like me to answer about this image?
Error processing 2324.jpg: 'choices'
Error processing 2744.jpg: 'choices'
3058 | I don't see a specific question in the image. The image appears to be a large block of text or code in a dark color against a light background. Could you please clarify what question you would like me to answer about this image?
3429 | I apologize, but I'm unable to see any question in the image. The image appears to be a large table or grid with multiple cells, but I cannot make out any specific question that needs to be answered. Could you please share the question you'd like me to help with?
Results saved to: test\test.json


## Deepinfra(Llama & Qwen)

In [112]:
import os
import base64
import json
from openai import OpenAI

def process_images(folder_path):
    openai = OpenAI(
    api_key="G0QudzLa9xY2YYUIKqKV6qgbF7HpLyTf",
    base_url="https://api.deepinfra.com/v1/openai",
    )
    results = {}  
    valid_extensions = ('.jpg', '.jpeg', '.png')
    image_files = [f for f in os.listdir(folder_path) if f.lower().endswith(valid_extensions)]
    
    for img_file in image_files:
        key = os.path.splitext(img_file)[0]
        img_path = os.path.join(folder_path, img_file)
        
        try:
            # Read and encode image with proper data URI format
            with open(img_path, 'rb') as f:
                img_base = base64.b64encode(f.read()).decode('utf-8')
                # Add the appropriate data URI prefix based on file extension
                if img_file.lower().endswith(('.jpg', '.jpeg')):
                    img_base = f"data:image/jpeg;base64,{img_base}"
                elif img_file.lower().endswith('.png'):
                    img_base = f"data:image/png;base64,{img_base}"
            
            response = openai.chat.completions.create(
                model="meta-llama/Llama-3.2-90B-Vision-Instruct",
                messages=[{
                    "role": "user", 
                    "content":[
                        {"type": "image_url", "image_url": {"url": img_base}},
                        {"type": "text", "text": "concisely answer the question on the image"}
                    ]
                }],
            )
                        
            value = response.choices[0].message.content
            results[key] = value
            print(key,'|',value)
            
        except Exception as e:
            print(f"Error processing {img_file}: {str(e)}")
            results[key] = "Error: " + str(e)
    
    output_file = os.path.join(folder_path, 'view.json')
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    
    return output_file

# Usage
folder_path = "a"
output_file = process_images(folder_path)
print(f"Results saved to: {output_file}")

0650 | The celebrity in the image is Tom Hanks.
Results saved to: a\view.json


## GLM

## Other

In [ ]:
import json
data = json.loads(response.text)
print(data['choices'][0]['message']['content'])

In [6]:
# Please install OpenAI SDK first: `pip3 install openai`

from openai import OpenAI

client = OpenAI(api_key="sk-53b8c802015f4ed795f873e74b67072a", base_url="https://api.deepseek.com")

response = client.chat.completions.create(
    model="deepseek-chat",
    messages=[
        {"role": "system", "content": "You are a helpful assistant"},
        {"role": "user", "content": "Hello,can you process image"},
    ],
    stream=False
)

print(response.choices[0].message.content)

Hello! Unfortunately, I cannot process or analyze images directly. However, if you describe the image or provide details about it, I can certainly help interpret or provide information based on your description. Let me know how I can assist!


In [119]:
import json

# Function to sum binary lists
def sum_binary_lists(data_dict):
    # Initialize result list with zeros
    result = [0] * 6  # Assuming all binary lists have length 6
    
    # Iterate through all items in dictionary
    for item in data_dict.values():
        binary_list = item[1]  # Get the binary list (second element)
        # Sum corresponding elements
        for i in range(len(binary_list)):
            result[i] += binary_list[i]
    
    return result

# Read from JSON file
with open('json/result_3.json', 'r') as f:
    data = json.load(f)

# Calculate sum
result = sum_binary_lists(data)
print(result)
# Write result to JSON file
# with open('output.json', 'w') as f:
#     json.dump(result, f)

[2418, 1929, 2749, 1807, 1777, 1066]


In [121]:
import json

def count_third_values(data_dict):
    # Initialize result list with zeros for numbers 0-6 (7 positions)
    result = [0] * 7
    
    # Count frequency of each number
    for item in data_dict.values():
        third_value = item[2]  # Get the third value
        result[third_value] += 1
    
    return result

# Read from JSON file
with open('json/result_3.json', 'r') as f:
    data = json.load(f)

# Calculate frequency
result = count_third_values(data)
print(result)

[285, 436, 516, 555, 586, 637, 514]


number of  0 to 6 recognitions:[285, 436, 516, 555, 586, 637, 514]. from this result ,we can further look into following interetsting points:
- for the number of 0 recognition(285),which means the number of images that all the LLMs fails to recognise, so when evaluating the recognition performance, it's better to evlauate against the number of at least one recognition(3529-285).
- for the total number of 1 recogintion(436),we can further look into ,each LLM contribute how much of these number.
- for the total number of 5 recognition(637),another interesting point is ,each LLM contribute how much to this number, which means, each LLM occupy how much percentage of in being the only one LLM that failed the specific task

## print out the presentation method

In [152]:
pre = """
Analyze visual representations of literature works and fictional characters. For each visual representation, identify which of these methods is used:

1. Illustration - Detailed artistic depiction of scenes, characters, or moments from literature works
2. Cartoon - Simplified or exaggerated drawing style for humorous effect
3. Caricature - Intentionally distorted features of characters for comic or satirical purposes
4. Emoji Combination - Multiple emojis merged to represent literary elements
5. Minimalism - Simplified visual representation using minimal design elements
6. Other - If none above, specify the visual method used

Rules:
- Choose only ONE method per visual representation
- If multiple methods seem applicable, select the one that appears earlier in the list
- For methods 1-5, respond with just the method name
- For method 6 (Other), provide the specific visual/artistic term that describes the method used

Example scenarios:
- A detailed painting of Alice falling down the rabbit hole → Illustration
- A whimsical, simplified drawing of Don Quixote fighting windmills → Cartoon
- An exaggerated sketch of Captain Ahab's obsessive expression → Caricature
- 🐺 + 👵 to represent Little Red Riding Hood → Emoji Combination
- Single line drawing to represent Odysseus's journey → Minimalism
- Abstract shapes representing the transformation in Kafka's Metamorphosis → Other (Abstract Symbolism)
"""